#!/bin/bash

# Demo script showing what narsil-mcp graph tools would reveal about Patina

echo "🔍 Patina Graph Analysis Demo"
echo "============================"

echo ""
echo "📊 What get_call_graph would show for the main 'run' function:"
echo "CALLERS of app::run:"
echo "  - main::main()"
echo ""
echo "CALLEES of app::run:"
echo "  - run_print_mode()"
echo "  - terminal::configure_iterm2_keybindings()"
echo "  - default_sessions_dir()"
echo "  - SessionManager::new()"
echo "  - load_session_state()"
echo "  - initialize_compression_orchestrator()"
echo "  - enable_raw_mode()"
echo "  - supports_keyboard_enhancement()"
echo "  - terminal::is_iterm2()"
echo "  - terminal::is_jetbrains_terminal()"
echo "  - AnthropicClient::new()"
echo "  - IdeController::new()"
echo "  - event_loop()"

echo ""
echo "🔥 What get_function_hotspots would identify:"
echo "HIGH-CONNECTIVITY FUNCTIONS (potential refactoring targets):"
echo "  - AppState::* (methods called from many places)"
echo "  - event_loop() (central coordination point)"
echo "  - state.* (heavy state management)"
echo "  - client.* (API interaction hub)"

echo ""
echo "📈 What get_complexity would show:"
echo "COMPLEXITY METRICS:"
echo "  - event_loop(): HIGH cyclomatic complexity (large tokio::select!)"
echo "  - run_print_mode(): MEDIUM complexity (tool execution loop)"
echo "  - handle_permission_key_event(): MEDIUM complexity (key mappings)"
echo "  - initialize_compression_orchestrator(): LOW-MEDIUM complexity"

echo ""
echo "🔗 What find_call_path would show for run -> event_loop:"
echo "CALL PATH: main::main -> app::run -> event_loop"
echo "INTERMEDIATE CALLS:"
echo "  1. main() calls app::run()"
echo "  2. app::run() sets up state and terminal"
echo "  3. app::run() calls event_loop() with prepared context"

echo ""
echo "⚡ What get_callers would show for critical functions:"
echo ""
echo "CALLERS of event_loop():"
echo "  - app::run()"
echo ""
echo "CALLERS of start_tool_execution():"
echo "  - event_loop() (via background events)"
echo "  - handle_tool_execution()"
echo ""
echo "CALLERS of handle_copy():"
echo "  - event_loop() (keyboard handler for Cmd+C, Ctrl+Y)"

echo ""
echo "🎯 What get_callees would show for key functions:"
echo ""
echo "CALLEES of event_loop():"
echo "  - tui::render()"
echo "  - state.recv_background_event()"
echo "  - handle_permission_key_event()"
echo "  - handle_copy()"
echo "  - start_tool_execution()"
echo "  - finish_tool_execution_and_continue()"
echo "  - auto_save_session()"
echo ""
echo "CALLEES of start_tool_execution():"
echo "  - state.tool_loop_state()"
echo "  - state.approve_all_tools()"
echo "  - state.spawn_tool_execution()"
echo "  - state.set_loading()"

echo ""
echo "🏗️ Architecture Insights from Graph Analysis:"
echo "=============================================="
echo ""
echo "1. LAYERED ARCHITECTURE:"
echo "   - main() -> app::run() -> event_loop() (clear hierarchy)"
echo "   - Separation between interactive and print modes"
echo "   - Clean state management through AppState"
echo ""
echo "2. ASYNC COORDINATION:"
echo "   - event_loop() orchestrates multiple async streams"
echo "   - Tool execution happens in background tasks"
echo "   - Channel-based communication for results"
echo ""
echo "3. MODULAR DESIGN:"
echo "   - Terminal handling isolated in terminal::"
echo "   - MCP integration through narsil:: module"
echo "   - Permission system cleanly separated"
echo ""
echo "4. HOTSPOTS (Refactoring Candidates):"
echo "   - event_loop() is very large (500+ lines)"
echo "   - AppState has many responsibilities"
echo "   - Tool execution logic could be extracted"

echo ""
echo "✨ Graph visualization would show this as a hub-and-spoke pattern"
echo "   with event_loop() as the central hub coordinating:"
echo "   - UI events (keyboard, mouse)"
echo "   - API streaming"
echo "   - Tool execution"
echo "   - Session management"
echo "   - Permission handling"
