//! OpenAI Chat Completions API message types.
//!
//! These types represent the OpenAI-format request and response structures
//! used by OpenRouter and other OpenAI-compatible APIs. They are distinct
//! from Anthropic's message format and require bidirectional translation.
//!
//! # Overview
//!
//! The OpenAI Chat Completions API uses a different message structure than
//! Anthropic. Key differences:
//!
//! - Messages use `role` field with `system`/`user`/`assistant`/`tool` values
//! - Tool calls use `function` with `arguments` as a JSON **string** (not parsed object)
//! - Streaming uses `delta` objects within `choices` arrays
//! - Finish reasons use `stop`/`tool_calls`/`length` instead of Anthropic's `end_turn`/`tool_use`/`max_tokens`
//!
//! # References
//!
//! - [OpenAI Chat Completions API](https://platform.openai.com/docs/api-reference/chat)
//! - [OpenRouter API](https://openrouter.ai/docs)
//!
//! # Example
//!
//! ```rust
//! use patina::api::providers::openai_types::{OpenAiMessage, OpenAiRole};
//!
//! let msg = OpenAiMessage::user("Hello, how are you?");
//! assert_eq!(msg.role, OpenAiRole::User);
//! assert_eq!(msg.content.as_deref(), Some("Hello, how are you?"));
//! ```

use serde::{Deserialize, Serialize};
use serde_json::Value;

// =============================================================================
// Roles and Finish Reasons
// =============================================================================

/// Message role in the OpenAI Chat Completions API.
///
/// Each message in a conversation has a role that determines how the API
/// interprets it.
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::OpenAiRole;
///
/// let role = OpenAiRole::Assistant;
/// let json = serde_json::to_string(&role).unwrap();
/// assert_eq!(json, "\"assistant\"");
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum OpenAiRole {
    /// System instructions that guide the model's behavior.
    System,
    /// User input in the conversation.
    User,
    /// Model-generated responses.
    Assistant,
    /// Tool execution results returned to the model.
    Tool,
}

/// Reason the model stopped generating tokens.
///
/// Determines whether the client should take action (e.g., execute tools)
/// or present the response to the user.
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::OpenAiFinishReason;
///
/// let reason: OpenAiFinishReason = serde_json::from_str("\"stop\"").unwrap();
/// assert_eq!(reason, OpenAiFinishReason::Stop);
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OpenAiFinishReason {
    /// The model finished generating naturally.
    Stop,
    /// The model wants to call one or more tools.
    ToolCalls,
    /// The response hit the token limit.
    Length,
    /// Content was filtered by the provider's safety system.
    ContentFilter,
}

// =============================================================================
// Message Types (Request and Response)
// =============================================================================

/// A message in the OpenAI Chat Completions format.
///
/// This unified struct represents messages for all roles. Optional fields
/// are used depending on the role:
///
/// - **System**: `content` only
/// - **User**: `content` only (or `name` for multi-user scenarios)
/// - **Assistant**: `content` and/or `tool_calls`
/// - **Tool**: `content` and `tool_call_id`
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::OpenAiMessage;
///
/// // Simple user message
/// let msg = OpenAiMessage::user("What's the weather?");
///
/// // System instruction
/// let sys = OpenAiMessage::system("You are a helpful assistant.");
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiMessage {
    /// The role of the message author.
    pub role: OpenAiRole,

    /// The content of the message. `None` for assistant messages that only
    /// contain tool calls.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// An optional name for the participant (for multi-user conversations).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Tool calls generated by the model (assistant messages only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<OpenAiToolCall>>,

    /// The ID of the tool call this message responds to (tool messages only).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
}

impl OpenAiMessage {
    /// Creates a system message.
    #[must_use]
    pub fn system(content: impl Into<String>) -> Self {
        Self {
            role: OpenAiRole::System,
            content: Some(content.into()),
            name: None,
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates a user message.
    #[must_use]
    pub fn user(content: impl Into<String>) -> Self {
        Self {
            role: OpenAiRole::User,
            content: Some(content.into()),
            name: None,
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates an assistant message with text content.
    #[must_use]
    pub fn assistant(content: impl Into<String>) -> Self {
        Self {
            role: OpenAiRole::Assistant,
            content: Some(content.into()),
            name: None,
            tool_calls: None,
            tool_call_id: None,
        }
    }

    /// Creates an assistant message with tool calls (content is null).
    #[must_use]
    pub fn assistant_with_tool_calls(tool_calls: Vec<OpenAiToolCall>) -> Self {
        Self {
            role: OpenAiRole::Assistant,
            content: None,
            name: None,
            tool_calls: Some(tool_calls),
            tool_call_id: None,
        }
    }

    /// Creates a tool result message.
    #[must_use]
    pub fn tool(tool_call_id: impl Into<String>, content: impl Into<String>) -> Self {
        Self {
            role: OpenAiRole::Tool,
            content: Some(content.into()),
            name: None,
            tool_calls: None,
            tool_call_id: Some(tool_call_id.into()),
        }
    }
}

/// A tool call generated by the model.
///
/// In the OpenAI format, tool calls always have `type: "function"`.
/// The `function` field contains the function name and arguments as a
/// JSON-encoded string.
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::{OpenAiToolCall, OpenAiFunctionCall};
///
/// let call = OpenAiToolCall {
///     id: "call_abc123".to_string(),
///     call_type: "function".to_string(),
///     function: OpenAiFunctionCall {
///         name: "get_weather".to_string(),
///         arguments: r#"{"location":"Boston"}"#.to_string(),
///     },
/// };
/// assert_eq!(call.function.name, "get_weather");
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiToolCall {
    /// Unique identifier for this tool call.
    pub id: String,

    /// Always `"function"` in the current API.
    #[serde(rename = "type")]
    pub call_type: String,

    /// The function to call with its arguments.
    pub function: OpenAiFunctionCall,
}

impl OpenAiToolCall {
    /// Creates a new function tool call.
    ///
    /// # Arguments
    ///
    /// * `id` - Unique call identifier (e.g., "call_abc123")
    /// * `name` - Function name to call
    /// * `arguments` - JSON-encoded string of arguments
    #[must_use]
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        arguments: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            call_type: "function".to_string(),
            function: OpenAiFunctionCall {
                name: name.into(),
                arguments: arguments.into(),
            },
        }
    }
}

/// Function call details within a tool call.
///
/// Note that `arguments` is a JSON-encoded **string**, not a parsed JSON
/// object. This matches the OpenAI API specification where arguments are
/// streamed as string fragments that must be concatenated before parsing.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiFunctionCall {
    /// The name of the function to call.
    pub name: String,

    /// The arguments as a JSON-encoded string.
    pub arguments: String,
}

// =============================================================================
// Tool Definitions (Request)
// =============================================================================

/// A tool definition in the OpenAI format.
///
/// Tools are wrapped in a `type: "function"` envelope with the function
/// definition inside.
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::{OpenAiTool, OpenAiFunctionDef};
/// use serde_json::json;
///
/// let tool = OpenAiTool::function(
///     "get_weather",
///     "Get the current weather",
///     json!({"type": "object", "properties": {"location": {"type": "string"}}}),
/// );
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiTool {
    /// Always `"function"` in the current API.
    #[serde(rename = "type")]
    pub tool_type: String,

    /// The function definition.
    pub function: OpenAiFunctionDef,
}

impl OpenAiTool {
    /// Creates a function tool definition.
    #[must_use]
    pub fn function(
        name: impl Into<String>,
        description: impl Into<String>,
        parameters: Value,
    ) -> Self {
        Self {
            tool_type: "function".to_string(),
            function: OpenAiFunctionDef {
                name: name.into(),
                description: Some(description.into()),
                parameters: Some(parameters),
            },
        }
    }
}

/// Function definition within a tool.
///
/// Describes the function name, what it does, and its parameter schema.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiFunctionDef {
    /// The name of the function.
    pub name: String,

    /// Description of what the function does.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// JSON Schema for the function's parameters.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Value>,
}

// =============================================================================
// Tool Choice (Request)
// =============================================================================

/// Tool choice constraint for the API request.
///
/// Controls how the model selects tools. Can be a keyword string
/// (`"none"`, `"auto"`, `"required"`) or a specific function.
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::OpenAiToolChoice;
///
/// // Let the model decide
/// let auto = OpenAiToolChoice::auto();
/// let json = serde_json::to_string(&auto).unwrap();
/// assert_eq!(json, "\"auto\"");
///
/// // Require a specific function
/// let specific = OpenAiToolChoice::function("get_weather");
/// let json = serde_json::to_string(&specific).unwrap();
/// assert!(json.contains("get_weather"));
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(untagged)]
pub enum OpenAiToolChoice {
    /// A keyword choice: `"none"`, `"auto"`, or `"required"`.
    Keyword(String),

    /// A specific function that the model must call.
    Named(OpenAiNamedToolChoice),
}

impl OpenAiToolChoice {
    /// Disables tool use entirely.
    #[must_use]
    pub fn none() -> Self {
        Self::Keyword("none".to_string())
    }

    /// Lets the model decide whether to use tools.
    #[must_use]
    pub fn auto() -> Self {
        Self::Keyword("auto".to_string())
    }

    /// Requires the model to use at least one tool.
    #[must_use]
    pub fn required() -> Self {
        Self::Keyword("required".to_string())
    }

    /// Requires the model to call a specific function.
    #[must_use]
    pub fn function(name: impl Into<String>) -> Self {
        Self::Named(OpenAiNamedToolChoice {
            tool_type: "function".to_string(),
            function: OpenAiToolChoiceFunction { name: name.into() },
        })
    }
}

/// A named tool choice specifying a particular function.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiNamedToolChoice {
    /// Always `"function"`.
    #[serde(rename = "type")]
    pub tool_type: String,

    /// The function to require.
    pub function: OpenAiToolChoiceFunction,
}

/// Function name within a named tool choice.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiToolChoiceFunction {
    /// The name of the function the model must call.
    pub name: String,
}

// =============================================================================
// Non-Streaming Response
// =============================================================================

/// A complete (non-streaming) response from the Chat Completions API.
///
/// Contains one or more choices with the model's response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiResponse {
    /// Unique identifier for this completion.
    pub id: String,

    /// Object type, always `"chat.completion"`.
    pub object: String,

    /// Unix timestamp of when the completion was created.
    pub created: u64,

    /// The model that generated the completion.
    pub model: String,

    /// The list of completion choices.
    pub choices: Vec<OpenAiChoice>,

    /// Token usage statistics.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<OpenAiUsage>,
}

/// A single choice in a non-streaming response.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiChoice {
    /// The index of this choice in the choices array.
    pub index: u32,

    /// The assistant's response message.
    pub message: OpenAiMessage,

    /// The reason the model stopped generating.
    pub finish_reason: OpenAiFinishReason,
}

/// Token usage statistics.
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::OpenAiUsage;
///
/// let usage = OpenAiUsage {
///     prompt_tokens: 10,
///     completion_tokens: 20,
///     total_tokens: 30,
/// };
/// assert_eq!(usage.total_tokens, usage.prompt_tokens + usage.completion_tokens);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct OpenAiUsage {
    /// Number of tokens in the prompt.
    pub prompt_tokens: u32,

    /// Number of tokens in the generated completion.
    pub completion_tokens: u32,

    /// Total tokens used (prompt + completion).
    pub total_tokens: u32,
}

// =============================================================================
// Streaming Response Types
// =============================================================================

/// A Server-Sent Event chunk from the streaming Chat Completions API.
///
/// Each chunk contains partial response data in the `choices` array.
/// The `delta` field within each choice contains the incremental update.
///
/// # Examples
///
/// ```rust
/// use patina::api::providers::openai_types::OpenAiStreamChunk;
///
/// let json = r#"{
///     "id": "chatcmpl-abc",
///     "object": "chat.completion.chunk",
///     "created": 1694268190,
///     "model": "gpt-4",
///     "choices": [{
///         "index": 0,
///         "delta": {"content": "Hello"},
///         "finish_reason": null
///     }]
/// }"#;
///
/// let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
/// assert_eq!(chunk.choices[0].delta.content.as_deref(), Some("Hello"));
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiStreamChunk {
    /// Unique identifier for this completion (shared across all chunks).
    pub id: String,

    /// Object type, always `"chat.completion.chunk"`.
    pub object: String,

    /// Unix timestamp of when the completion was created.
    pub created: u64,

    /// The model that generated the completion.
    pub model: String,

    /// The list of streaming choices (usually one).
    pub choices: Vec<OpenAiStreamChoice>,

    /// Token usage (only present in the final chunk if requested).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<OpenAiUsage>,
}

/// A single choice in a streaming response chunk.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiStreamChoice {
    /// The index of this choice.
    pub index: u32,

    /// The incremental update for this choice.
    pub delta: OpenAiDelta,

    /// The finish reason, present only in the final chunk.
    pub finish_reason: Option<OpenAiFinishReason>,
}

/// Incremental content in a streaming choice.
///
/// Each delta can contain a subset of message fields. The first delta
/// typically contains `role`, subsequent deltas contain `content` or
/// `tool_calls`, and the final delta is empty with `finish_reason` set.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
pub struct OpenAiDelta {
    /// The role (present only in the first chunk).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub role: Option<OpenAiRole>,

    /// Text content fragment.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,

    /// Partial tool calls being streamed.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Vec<OpenAiToolCallDelta>>,
}

/// A partial tool call in a streaming delta.
///
/// The first delta for a tool call contains `id`, `type`, and the function
/// `name`. Subsequent deltas contain only `index` and argument fragments.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiToolCallDelta {
    /// Index of this tool call (for correlating across chunks).
    pub index: u32,

    /// The tool call ID (present only in the first chunk for this call).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// Always `"function"` (present only in the first chunk).
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub call_type: Option<String>,

    /// Partial function details.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function: Option<OpenAiFunctionCallDelta>,
}

/// Partial function call details in a streaming delta.
///
/// In the first chunk, `name` is present. In subsequent chunks,
/// only `arguments` fragments are sent.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct OpenAiFunctionCallDelta {
    /// The function name (present only in the first chunk).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// A fragment of the JSON-encoded arguments string.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}

// =============================================================================
// Conversions from Patina types
// =============================================================================

impl From<crate::api::tools::ToolDefinition> for OpenAiTool {
    /// Converts a Patina [`ToolDefinition`](crate::api::tools::ToolDefinition) to the
    /// OpenAI tool format.
    ///
    /// Maps `input_schema` to `parameters` and wraps in `type: "function"`.
    fn from(tool: crate::api::tools::ToolDefinition) -> Self {
        Self {
            tool_type: "function".to_string(),
            function: OpenAiFunctionDef {
                name: tool.name,
                description: Some(tool.description),
                parameters: Some(tool.input_schema),
            },
        }
    }
}

impl From<crate::api::tools::ToolChoice> for OpenAiToolChoice {
    /// Converts a Patina [`ToolChoice`](crate::api::tools::ToolChoice) to the OpenAI
    /// tool choice format.
    ///
    /// - `Auto` -> `"auto"`
    /// - `Any` -> `"required"` (closest OpenAI equivalent)
    /// - `Tool { name }` -> `{"type": "function", "function": {"name": "..."}}`
    fn from(choice: crate::api::tools::ToolChoice) -> Self {
        match choice {
            crate::api::tools::ToolChoice::Auto => Self::auto(),
            crate::api::tools::ToolChoice::Any => Self::required(),
            crate::api::tools::ToolChoice::Tool { name } => Self::function(name),
        }
    }
}

impl From<OpenAiFinishReason> for crate::types::content::StopReason {
    /// Converts an OpenAI finish reason to a Patina [`StopReason`](crate::types::content::StopReason).
    ///
    /// - `Stop` -> `EndTurn`
    /// - `ToolCalls` -> `ToolUse`
    /// - `Length` -> `MaxTokens`
    /// - `ContentFilter` -> `EndTurn` (treated as a terminal stop)
    fn from(reason: OpenAiFinishReason) -> Self {
        match reason {
            OpenAiFinishReason::Stop => Self::EndTurn,
            OpenAiFinishReason::ToolCalls => Self::ToolUse,
            OpenAiFinishReason::Length => Self::MaxTokens,
            OpenAiFinishReason::ContentFilter => Self::EndTurn,
        }
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    // =========================================================================
    // OpenAiRole serialization
    // =========================================================================

    #[test]
    fn test_role_system_serializes_as_lowercase() {
        let json = serde_json::to_string(&OpenAiRole::System).unwrap();
        assert_eq!(json, "\"system\"");
    }

    #[test]
    fn test_role_user_serializes_as_lowercase() {
        let json = serde_json::to_string(&OpenAiRole::User).unwrap();
        assert_eq!(json, "\"user\"");
    }

    #[test]
    fn test_role_assistant_serializes_as_lowercase() {
        let json = serde_json::to_string(&OpenAiRole::Assistant).unwrap();
        assert_eq!(json, "\"assistant\"");
    }

    #[test]
    fn test_role_tool_serializes_as_lowercase() {
        let json = serde_json::to_string(&OpenAiRole::Tool).unwrap();
        assert_eq!(json, "\"tool\"");
    }

    #[test]
    fn test_role_round_trip() {
        for role in [
            OpenAiRole::System,
            OpenAiRole::User,
            OpenAiRole::Assistant,
            OpenAiRole::Tool,
        ] {
            let json = serde_json::to_string(&role).unwrap();
            let parsed: OpenAiRole = serde_json::from_str(&json).unwrap();
            assert_eq!(role, parsed);
        }
    }

    // =========================================================================
    // OpenAiFinishReason serialization
    // =========================================================================

    #[test]
    fn test_finish_reason_stop_serialization() {
        let json = serde_json::to_string(&OpenAiFinishReason::Stop).unwrap();
        assert_eq!(json, "\"stop\"");
    }

    #[test]
    fn test_finish_reason_tool_calls_serialization() {
        let json = serde_json::to_string(&OpenAiFinishReason::ToolCalls).unwrap();
        assert_eq!(json, "\"tool_calls\"");
    }

    #[test]
    fn test_finish_reason_length_serialization() {
        let json = serde_json::to_string(&OpenAiFinishReason::Length).unwrap();
        assert_eq!(json, "\"length\"");
    }

    #[test]
    fn test_finish_reason_content_filter_serialization() {
        let json = serde_json::to_string(&OpenAiFinishReason::ContentFilter).unwrap();
        assert_eq!(json, "\"content_filter\"");
    }

    #[test]
    fn test_finish_reason_round_trip() {
        for reason in [
            OpenAiFinishReason::Stop,
            OpenAiFinishReason::ToolCalls,
            OpenAiFinishReason::Length,
            OpenAiFinishReason::ContentFilter,
        ] {
            let json = serde_json::to_string(&reason).unwrap();
            let parsed: OpenAiFinishReason = serde_json::from_str(&json).unwrap();
            assert_eq!(reason, parsed);
        }
    }

    // =========================================================================
    // OpenAiMessage construction and serialization
    // =========================================================================

    #[test]
    fn test_user_message_construction() {
        let msg = OpenAiMessage::user("Hello");
        assert_eq!(msg.role, OpenAiRole::User);
        assert_eq!(msg.content.as_deref(), Some("Hello"));
        assert!(msg.tool_calls.is_none());
        assert!(msg.tool_call_id.is_none());
        assert!(msg.name.is_none());
    }

    #[test]
    fn test_system_message_construction() {
        let msg = OpenAiMessage::system("You are helpful");
        assert_eq!(msg.role, OpenAiRole::System);
        assert_eq!(msg.content.as_deref(), Some("You are helpful"));
    }

    #[test]
    fn test_assistant_message_construction() {
        let msg = OpenAiMessage::assistant("I can help!");
        assert_eq!(msg.role, OpenAiRole::Assistant);
        assert_eq!(msg.content.as_deref(), Some("I can help!"));
    }

    #[test]
    fn test_tool_message_construction() {
        let msg = OpenAiMessage::tool("call_123", "file contents here");
        assert_eq!(msg.role, OpenAiRole::Tool);
        assert_eq!(msg.content.as_deref(), Some("file contents here"));
        assert_eq!(msg.tool_call_id.as_deref(), Some("call_123"));
    }

    #[test]
    fn test_assistant_with_tool_calls_construction() {
        let calls = vec![OpenAiToolCall::new(
            "call_abc",
            "get_weather",
            r#"{"location":"Boston"}"#,
        )];
        let msg = OpenAiMessage::assistant_with_tool_calls(calls);
        assert_eq!(msg.role, OpenAiRole::Assistant);
        assert!(msg.content.is_none());
        assert_eq!(msg.tool_calls.as_ref().unwrap().len(), 1);
    }

    #[test]
    fn test_user_message_serialization_matches_spec() {
        let msg = OpenAiMessage::user("Hello");
        let json = serde_json::to_value(&msg).unwrap();

        assert_eq!(json["role"], "user");
        assert_eq!(json["content"], "Hello");
        // Optional fields should not be present
        assert!(json.get("tool_calls").is_none());
        assert!(json.get("tool_call_id").is_none());
        assert!(json.get("name").is_none());
    }

    #[test]
    fn test_system_message_serialization_matches_spec() {
        let msg = OpenAiMessage::system("Be concise");
        let json = serde_json::to_value(&msg).unwrap();

        assert_eq!(json["role"], "system");
        assert_eq!(json["content"], "Be concise");
    }

    #[test]
    fn test_assistant_message_with_tool_calls_serialization() {
        let msg = OpenAiMessage::assistant_with_tool_calls(vec![OpenAiToolCall::new(
            "call_123",
            "bash",
            r#"{"command":"ls"}"#,
        )]);
        let json = serde_json::to_value(&msg).unwrap();

        assert_eq!(json["role"], "assistant");
        // content should not be present when None
        assert!(json.get("content").is_none());
        assert!(json["tool_calls"].is_array());
        assert_eq!(json["tool_calls"][0]["id"], "call_123");
        assert_eq!(json["tool_calls"][0]["type"], "function");
        assert_eq!(json["tool_calls"][0]["function"]["name"], "bash");
        assert_eq!(
            json["tool_calls"][0]["function"]["arguments"],
            r#"{"command":"ls"}"#
        );
    }

    #[test]
    fn test_tool_message_serialization_matches_spec() {
        let msg = OpenAiMessage::tool("call_123", "output text");
        let json = serde_json::to_value(&msg).unwrap();

        assert_eq!(json["role"], "tool");
        assert_eq!(json["content"], "output text");
        assert_eq!(json["tool_call_id"], "call_123");
    }

    #[test]
    fn test_user_message_round_trip() {
        let msg = OpenAiMessage::user("Hello");
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: OpenAiMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, parsed);
    }

    #[test]
    fn test_assistant_tool_calls_round_trip() {
        let msg = OpenAiMessage::assistant_with_tool_calls(vec![
            OpenAiToolCall::new("call_1", "bash", r#"{"cmd":"ls"}"#),
            OpenAiToolCall::new("call_2", "read_file", r#"{"path":"foo.rs"}"#),
        ]);
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: OpenAiMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, parsed);
    }

    #[test]
    fn test_tool_message_round_trip() {
        let msg = OpenAiMessage::tool("call_abc", "result data");
        let json = serde_json::to_string(&msg).unwrap();
        let parsed: OpenAiMessage = serde_json::from_str(&json).unwrap();
        assert_eq!(msg, parsed);
    }

    #[test]
    fn test_message_deserialization_from_api_json() {
        // Exact format as returned by OpenAI API
        let json = r#"{
            "role": "assistant",
            "content": null,
            "tool_calls": [{
                "id": "call_abc123",
                "type": "function",
                "function": {
                    "name": "get_weather",
                    "arguments": "{\"location\":\"Boston\",\"unit\":\"fahrenheit\"}"
                }
            }]
        }"#;

        let msg: OpenAiMessage = serde_json::from_str(json).unwrap();
        assert_eq!(msg.role, OpenAiRole::Assistant);
        assert!(msg.content.is_none());
        let calls = msg.tool_calls.unwrap();
        assert_eq!(calls.len(), 1);
        assert_eq!(calls[0].id, "call_abc123");
        assert_eq!(calls[0].call_type, "function");
        assert_eq!(calls[0].function.name, "get_weather");
        assert!(calls[0].function.arguments.contains("Boston"));
    }

    // =========================================================================
    // OpenAiToolCall
    // =========================================================================

    #[test]
    fn test_tool_call_new() {
        let call = OpenAiToolCall::new("call_1", "bash", r#"{"cmd":"pwd"}"#);
        assert_eq!(call.id, "call_1");
        assert_eq!(call.call_type, "function");
        assert_eq!(call.function.name, "bash");
        assert_eq!(call.function.arguments, r#"{"cmd":"pwd"}"#);
    }

    #[test]
    fn test_tool_call_serialization_has_type_function() {
        let call = OpenAiToolCall::new("call_1", "bash", "{}");
        let json = serde_json::to_value(&call).unwrap();

        assert_eq!(json["type"], "function");
        assert_eq!(json["id"], "call_1");
        assert_eq!(json["function"]["name"], "bash");
        assert_eq!(json["function"]["arguments"], "{}");
    }

    #[test]
    fn test_tool_call_arguments_is_string_not_object() {
        let call = OpenAiToolCall::new("call_1", "bash", r#"{"command":"ls -la"}"#);
        let json = serde_json::to_value(&call).unwrap();

        // arguments must be a string, not a parsed JSON object
        assert!(
            json["function"]["arguments"].is_string(),
            "arguments should be a string, not an object"
        );
    }

    #[test]
    fn test_tool_call_round_trip() {
        let call = OpenAiToolCall::new("call_xyz", "read_file", r#"{"path":"src/main.rs"}"#);
        let json = serde_json::to_string(&call).unwrap();
        let parsed: OpenAiToolCall = serde_json::from_str(&json).unwrap();
        assert_eq!(call, parsed);
    }

    // =========================================================================
    // OpenAiTool (tool definitions)
    // =========================================================================

    #[test]
    fn test_tool_definition_construction() {
        let tool = OpenAiTool::function(
            "bash",
            "Run a command",
            json!({"type": "object", "properties": {"command": {"type": "string"}}}),
        );
        assert_eq!(tool.tool_type, "function");
        assert_eq!(tool.function.name, "bash");
        assert_eq!(tool.function.description.as_deref(), Some("Run a command"));
    }

    #[test]
    fn test_tool_definition_serialization_matches_spec() {
        let tool = OpenAiTool::function(
            "get_weather",
            "Get weather info",
            json!({
                "type": "object",
                "properties": {
                    "location": {"type": "string"}
                },
                "required": ["location"]
            }),
        );
        let json = serde_json::to_value(&tool).unwrap();

        assert_eq!(json["type"], "function");
        assert_eq!(json["function"]["name"], "get_weather");
        assert_eq!(json["function"]["description"], "Get weather info");
        assert_eq!(json["function"]["parameters"]["type"], "object");
    }

    #[test]
    fn test_tool_definition_round_trip() {
        let tool = OpenAiTool::function("bash", "Run commands", json!({"type": "object"}));
        let json = serde_json::to_string(&tool).unwrap();
        let parsed: OpenAiTool = serde_json::from_str(&json).unwrap();
        assert_eq!(tool, parsed);
    }

    // =========================================================================
    // OpenAiToolChoice
    // =========================================================================

    #[test]
    fn test_tool_choice_none_serialization() {
        let choice = OpenAiToolChoice::none();
        let json = serde_json::to_string(&choice).unwrap();
        assert_eq!(json, "\"none\"");
    }

    #[test]
    fn test_tool_choice_auto_serialization() {
        let choice = OpenAiToolChoice::auto();
        let json = serde_json::to_string(&choice).unwrap();
        assert_eq!(json, "\"auto\"");
    }

    #[test]
    fn test_tool_choice_required_serialization() {
        let choice = OpenAiToolChoice::required();
        let json = serde_json::to_string(&choice).unwrap();
        assert_eq!(json, "\"required\"");
    }

    #[test]
    fn test_tool_choice_function_serialization() {
        let choice = OpenAiToolChoice::function("get_weather");
        let json = serde_json::to_value(&choice).unwrap();

        assert_eq!(json["type"], "function");
        assert_eq!(json["function"]["name"], "get_weather");
    }

    #[test]
    fn test_tool_choice_auto_round_trip() {
        let choice = OpenAiToolChoice::auto();
        let json = serde_json::to_string(&choice).unwrap();
        let parsed: OpenAiToolChoice = serde_json::from_str(&json).unwrap();
        assert_eq!(choice, parsed);
    }

    #[test]
    fn test_tool_choice_function_round_trip() {
        let choice = OpenAiToolChoice::function("bash");
        let json = serde_json::to_string(&choice).unwrap();
        let parsed: OpenAiToolChoice = serde_json::from_str(&json).unwrap();
        assert_eq!(choice, parsed);
    }

    // =========================================================================
    // OpenAiResponse (non-streaming)
    // =========================================================================

    #[test]
    fn test_response_deserialization_text() {
        let json = r#"{
            "id": "chatcmpl-abc123",
            "object": "chat.completion",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": "Hello! How can I help?"
                },
                "finish_reason": "stop"
            }],
            "usage": {
                "prompt_tokens": 10,
                "completion_tokens": 8,
                "total_tokens": 18
            }
        }"#;

        let resp: OpenAiResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.id, "chatcmpl-abc123");
        assert_eq!(resp.object, "chat.completion");
        assert_eq!(resp.model, "gpt-4");
        assert_eq!(resp.choices.len(), 1);
        assert_eq!(resp.choices[0].index, 0);
        assert_eq!(resp.choices[0].finish_reason, OpenAiFinishReason::Stop);
        assert_eq!(
            resp.choices[0].message.content.as_deref(),
            Some("Hello! How can I help?")
        );

        let usage = resp.usage.unwrap();
        assert_eq!(usage.prompt_tokens, 10);
        assert_eq!(usage.completion_tokens, 8);
        assert_eq!(usage.total_tokens, 18);
    }

    #[test]
    fn test_response_deserialization_with_tool_calls() {
        let json = r#"{
            "id": "chatcmpl-abc123",
            "object": "chat.completion",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": null,
                    "tool_calls": [{
                        "id": "call_abc",
                        "type": "function",
                        "function": {
                            "name": "bash",
                            "arguments": "{\"command\":\"ls\"}"
                        }
                    }]
                },
                "finish_reason": "tool_calls"
            }],
            "usage": {
                "prompt_tokens": 20,
                "completion_tokens": 15,
                "total_tokens": 35
            }
        }"#;

        let resp: OpenAiResponse = serde_json::from_str(json).unwrap();
        assert_eq!(resp.choices[0].finish_reason, OpenAiFinishReason::ToolCalls);
        let msg = &resp.choices[0].message;
        assert!(msg.content.is_none());
        let calls = msg.tool_calls.as_ref().unwrap();
        assert_eq!(calls[0].function.name, "bash");
    }

    #[test]
    fn test_response_round_trip() {
        let resp = OpenAiResponse {
            id: "chatcmpl-test".to_string(),
            object: "chat.completion".to_string(),
            created: 1694268190,
            model: "gpt-4".to_string(),
            choices: vec![OpenAiChoice {
                index: 0,
                message: OpenAiMessage::assistant("Hello"),
                finish_reason: OpenAiFinishReason::Stop,
            }],
            usage: Some(OpenAiUsage {
                prompt_tokens: 5,
                completion_tokens: 1,
                total_tokens: 6,
            }),
        };
        let json = serde_json::to_string(&resp).unwrap();
        let parsed: OpenAiResponse = serde_json::from_str(&json).unwrap();
        assert_eq!(resp, parsed);
    }

    // =========================================================================
    // OpenAiUsage
    // =========================================================================

    #[test]
    fn test_usage_serialization() {
        let usage = OpenAiUsage {
            prompt_tokens: 100,
            completion_tokens: 50,
            total_tokens: 150,
        };
        let json = serde_json::to_value(&usage).unwrap();
        assert_eq!(json["prompt_tokens"], 100);
        assert_eq!(json["completion_tokens"], 50);
        assert_eq!(json["total_tokens"], 150);
    }

    #[test]
    fn test_usage_round_trip() {
        let usage = OpenAiUsage {
            prompt_tokens: 42,
            completion_tokens: 17,
            total_tokens: 59,
        };
        let json = serde_json::to_string(&usage).unwrap();
        let parsed: OpenAiUsage = serde_json::from_str(&json).unwrap();
        assert_eq!(usage, parsed);
    }

    // =========================================================================
    // OpenAiStreamChunk (streaming responses)
    // =========================================================================

    #[test]
    fn test_stream_chunk_first_with_role() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {
                    "role": "assistant",
                    "content": ""
                },
                "finish_reason": null
            }]
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        assert_eq!(chunk.id, "chatcmpl-abc");
        assert_eq!(chunk.object, "chat.completion.chunk");
        assert_eq!(chunk.choices.len(), 1);
        assert_eq!(chunk.choices[0].delta.role, Some(OpenAiRole::Assistant));
        assert_eq!(chunk.choices[0].delta.content.as_deref(), Some(""));
        assert!(chunk.choices[0].finish_reason.is_none());
    }

    #[test]
    fn test_stream_chunk_content_delta() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {
                    "content": "Hello"
                },
                "finish_reason": null
            }]
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        assert_eq!(chunk.choices[0].delta.content.as_deref(), Some("Hello"));
        assert!(chunk.choices[0].delta.role.is_none());
    }

    #[test]
    fn test_stream_chunk_tool_call_start() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {
                    "tool_calls": [{
                        "index": 0,
                        "id": "call_abc",
                        "type": "function",
                        "function": {
                            "name": "get_weather",
                            "arguments": ""
                        }
                    }]
                },
                "finish_reason": null
            }]
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        let tool_calls = chunk.choices[0].delta.tool_calls.as_ref().unwrap();
        assert_eq!(tool_calls.len(), 1);
        assert_eq!(tool_calls[0].index, 0);
        assert_eq!(tool_calls[0].id.as_deref(), Some("call_abc"));
        assert_eq!(tool_calls[0].call_type.as_deref(), Some("function"));
        let func = tool_calls[0].function.as_ref().unwrap();
        assert_eq!(func.name.as_deref(), Some("get_weather"));
        assert_eq!(func.arguments.as_deref(), Some(""));
    }

    #[test]
    fn test_stream_chunk_tool_call_arguments_fragment() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {
                    "tool_calls": [{
                        "index": 0,
                        "function": {
                            "arguments": "{\"loc"
                        }
                    }]
                },
                "finish_reason": null
            }]
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        let tool_calls = chunk.choices[0].delta.tool_calls.as_ref().unwrap();
        assert_eq!(tool_calls[0].index, 0);
        // id and type should not be present in argument-only chunks
        assert!(tool_calls[0].id.is_none());
        assert!(tool_calls[0].call_type.is_none());
        let func = tool_calls[0].function.as_ref().unwrap();
        assert!(func.name.is_none());
        assert_eq!(func.arguments.as_deref(), Some("{\"loc"));
    }

    #[test]
    fn test_stream_chunk_finish_stop() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {},
                "finish_reason": "stop"
            }]
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        assert_eq!(
            chunk.choices[0].finish_reason,
            Some(OpenAiFinishReason::Stop)
        );
        // Delta should be empty
        assert!(chunk.choices[0].delta.role.is_none());
        assert!(chunk.choices[0].delta.content.is_none());
        assert!(chunk.choices[0].delta.tool_calls.is_none());
    }

    #[test]
    fn test_stream_chunk_finish_tool_calls() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {},
                "finish_reason": "tool_calls"
            }]
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        assert_eq!(
            chunk.choices[0].finish_reason,
            Some(OpenAiFinishReason::ToolCalls)
        );
    }

    #[test]
    fn test_stream_chunk_with_usage() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {},
                "finish_reason": "stop"
            }],
            "usage": {
                "prompt_tokens": 10,
                "completion_tokens": 20,
                "total_tokens": 30
            }
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        let usage = chunk.usage.unwrap();
        assert_eq!(usage.prompt_tokens, 10);
        assert_eq!(usage.completion_tokens, 20);
        assert_eq!(usage.total_tokens, 30);
    }

    #[test]
    fn test_stream_chunk_round_trip_content() {
        let chunk = OpenAiStreamChunk {
            id: "chatcmpl-test".to_string(),
            object: "chat.completion.chunk".to_string(),
            created: 1694268190,
            model: "gpt-4".to_string(),
            choices: vec![OpenAiStreamChoice {
                index: 0,
                delta: OpenAiDelta {
                    role: None,
                    content: Some("Hello".to_string()),
                    tool_calls: None,
                },
                finish_reason: None,
            }],
            usage: None,
        };
        let json = serde_json::to_string(&chunk).unwrap();
        let parsed: OpenAiStreamChunk = serde_json::from_str(&json).unwrap();
        assert_eq!(chunk, parsed);
    }

    #[test]
    fn test_stream_chunk_round_trip_tool_call() {
        let chunk = OpenAiStreamChunk {
            id: "chatcmpl-test".to_string(),
            object: "chat.completion.chunk".to_string(),
            created: 1694268190,
            model: "gpt-4".to_string(),
            choices: vec![OpenAiStreamChoice {
                index: 0,
                delta: OpenAiDelta {
                    role: None,
                    content: None,
                    tool_calls: Some(vec![OpenAiToolCallDelta {
                        index: 0,
                        id: Some("call_abc".to_string()),
                        call_type: Some("function".to_string()),
                        function: Some(OpenAiFunctionCallDelta {
                            name: Some("bash".to_string()),
                            arguments: Some(String::new()),
                        }),
                    }]),
                },
                finish_reason: None,
            }],
            usage: None,
        };
        let json = serde_json::to_string(&chunk).unwrap();
        let parsed: OpenAiStreamChunk = serde_json::from_str(&json).unwrap();
        assert_eq!(chunk, parsed);
    }

    // =========================================================================
    // OpenAiDelta
    // =========================================================================

    #[test]
    fn test_delta_default_is_empty() {
        let delta = OpenAiDelta::default();
        assert!(delta.role.is_none());
        assert!(delta.content.is_none());
        assert!(delta.tool_calls.is_none());
    }

    #[test]
    fn test_empty_delta_serializes_as_empty_object() {
        let delta = OpenAiDelta::default();
        let json = serde_json::to_value(&delta).unwrap();
        assert_eq!(json, json!({}));
    }

    // =========================================================================
    // Edge cases and spec compliance
    // =========================================================================

    #[test]
    fn test_message_with_null_content_deserializes() {
        let json = r#"{"role":"assistant","content":null}"#;
        let msg: OpenAiMessage = serde_json::from_str(json).unwrap();
        assert_eq!(msg.role, OpenAiRole::Assistant);
        assert!(msg.content.is_none());
    }

    #[test]
    fn test_message_without_optional_fields_deserializes() {
        let json = r#"{"role":"user","content":"hi"}"#;
        let msg: OpenAiMessage = serde_json::from_str(json).unwrap();
        assert_eq!(msg.role, OpenAiRole::User);
        assert_eq!(msg.content.as_deref(), Some("hi"));
        assert!(msg.tool_calls.is_none());
        assert!(msg.tool_call_id.is_none());
        assert!(msg.name.is_none());
    }

    #[test]
    fn test_multiple_tool_calls_in_message() {
        let msg = OpenAiMessage::assistant_with_tool_calls(vec![
            OpenAiToolCall::new("call_1", "bash", r#"{"cmd":"ls"}"#),
            OpenAiToolCall::new("call_2", "read_file", r#"{"path":"README.md"}"#),
            OpenAiToolCall::new("call_3", "grep", r#"{"pattern":"fn main"}"#),
        ]);
        let json = serde_json::to_value(&msg).unwrap();
        assert_eq!(json["tool_calls"].as_array().unwrap().len(), 3);
    }

    #[test]
    fn test_stream_chunk_multiple_tool_call_deltas() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion.chunk",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "delta": {
                    "tool_calls": [
                        {
                            "index": 0,
                            "id": "call_1",
                            "type": "function",
                            "function": {"name": "bash", "arguments": ""}
                        },
                        {
                            "index": 1,
                            "id": "call_2",
                            "type": "function",
                            "function": {"name": "read_file", "arguments": ""}
                        }
                    ]
                },
                "finish_reason": null
            }]
        }"#;

        let chunk: OpenAiStreamChunk = serde_json::from_str(json).unwrap();
        let calls = chunk.choices[0].delta.tool_calls.as_ref().unwrap();
        assert_eq!(calls.len(), 2);
        assert_eq!(calls[0].index, 0);
        assert_eq!(calls[1].index, 1);
    }

    #[test]
    fn test_function_def_without_optional_fields() {
        let json = r#"{"name": "simple_fn"}"#;
        let def: OpenAiFunctionDef = serde_json::from_str(json).unwrap();
        assert_eq!(def.name, "simple_fn");
        assert!(def.description.is_none());
        assert!(def.parameters.is_none());
    }

    #[test]
    fn test_response_without_usage() {
        let json = r#"{
            "id": "chatcmpl-abc",
            "object": "chat.completion",
            "created": 1694268190,
            "model": "gpt-4",
            "choices": [{
                "index": 0,
                "message": {"role": "assistant", "content": "Hi"},
                "finish_reason": "stop"
            }]
        }"#;

        let resp: OpenAiResponse = serde_json::from_str(json).unwrap();
        assert!(resp.usage.is_none());
    }

    // =========================================================================
    // Send + Sync bounds (required for async contexts)
    // =========================================================================

    #[test]
    fn test_types_are_send() {
        fn assert_send<T: Send>() {}
        assert_send::<OpenAiMessage>();
        assert_send::<OpenAiToolCall>();
        assert_send::<OpenAiStreamChunk>();
        assert_send::<OpenAiDelta>();
        assert_send::<OpenAiResponse>();
        assert_send::<OpenAiTool>();
        assert_send::<OpenAiToolChoice>();
    }

    #[test]
    fn test_types_are_sync() {
        fn assert_sync<T: Sync>() {}
        assert_sync::<OpenAiMessage>();
        assert_sync::<OpenAiToolCall>();
        assert_sync::<OpenAiStreamChunk>();
        assert_sync::<OpenAiDelta>();
        assert_sync::<OpenAiResponse>();
        assert_sync::<OpenAiTool>();
        assert_sync::<OpenAiToolChoice>();
    }

    // =========================================================================
    // From conversions
    // =========================================================================

    #[test]
    fn test_tool_definition_to_openai_tool() {
        let patina_tool = crate::api::tools::ToolDefinition::new(
            "bash",
            "Run a command",
            json!({"type": "object", "properties": {"command": {"type": "string"}}}),
        );
        let openai_tool: OpenAiTool = patina_tool.into();

        assert_eq!(openai_tool.tool_type, "function");
        assert_eq!(openai_tool.function.name, "bash");
        assert_eq!(
            openai_tool.function.description.as_deref(),
            Some("Run a command")
        );
        assert_eq!(
            openai_tool.function.parameters.as_ref().unwrap()["type"],
            "object"
        );
    }

    #[test]
    fn test_tool_choice_auto_to_openai() {
        let patina_choice = crate::api::tools::ToolChoice::Auto;
        let openai_choice: OpenAiToolChoice = patina_choice.into();

        assert_eq!(openai_choice, OpenAiToolChoice::auto());
    }

    #[test]
    fn test_tool_choice_any_to_openai_required() {
        let patina_choice = crate::api::tools::ToolChoice::Any;
        let openai_choice: OpenAiToolChoice = patina_choice.into();

        // Anthropic "Any" maps to OpenAI "required"
        assert_eq!(openai_choice, OpenAiToolChoice::required());
    }

    #[test]
    fn test_tool_choice_tool_to_openai_function() {
        let patina_choice = crate::api::tools::ToolChoice::Tool {
            name: "bash".to_string(),
        };
        let openai_choice: OpenAiToolChoice = patina_choice.into();

        assert_eq!(openai_choice, OpenAiToolChoice::function("bash"));
    }

    #[test]
    fn test_finish_reason_stop_to_end_turn() {
        let stop_reason: crate::types::content::StopReason = OpenAiFinishReason::Stop.into();
        assert_eq!(stop_reason, crate::types::content::StopReason::EndTurn);
    }

    #[test]
    fn test_finish_reason_tool_calls_to_tool_use() {
        let stop_reason: crate::types::content::StopReason = OpenAiFinishReason::ToolCalls.into();
        assert_eq!(stop_reason, crate::types::content::StopReason::ToolUse);
    }

    #[test]
    fn test_finish_reason_length_to_max_tokens() {
        let stop_reason: crate::types::content::StopReason = OpenAiFinishReason::Length.into();
        assert_eq!(stop_reason, crate::types::content::StopReason::MaxTokens);
    }

    #[test]
    fn test_finish_reason_content_filter_to_end_turn() {
        let stop_reason: crate::types::content::StopReason =
            OpenAiFinishReason::ContentFilter.into();
        assert_eq!(stop_reason, crate::types::content::StopReason::EndTurn);
    }

    #[test]
    fn test_converted_tool_serializes_correctly() {
        let patina_tool = crate::api::tools::ToolDefinition::new(
            "read_file",
            "Read a file",
            json!({"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]}),
        );
        let openai_tool: OpenAiTool = patina_tool.into();
        let json = serde_json::to_value(&openai_tool).unwrap();

        // Must match OpenAI spec format
        assert_eq!(json["type"], "function");
        assert_eq!(json["function"]["name"], "read_file");
        assert_eq!(json["function"]["description"], "Read a file");
        assert_eq!(json["function"]["parameters"]["required"][0], "path");
    }
}
